{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "HackGSU.py",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyOe6HZ2JJwuWaRTUO8fstDY",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/atebeje1/seat-at-the-table/blob/main/database.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "INJLY_5RLvT0",
        "outputId": "cc1453f1-9d65-4c9b-e828-8b4950a0fb45"
      },
      "source": [
        "# source 1\n",
        "\n",
        "# import library that allows us to pull data from websites\n",
        "import requests\n",
        "\n",
        "# requests data from url below\n",
        "request = requests.get('https://www.adl.org/hate-symbols')\n",
        "content = request.content\n",
        "\n",
        "# imports library that allows for us to pick what parts of the content to pull\n",
        "from bs4 import BeautifulSoup\n",
        "\n",
        "# stores all of the site's content\n",
        "soup = BeautifulSoup(content)\n",
        "\n",
        "# filters soup to only display what is specified\n",
        "specificData = soup.find_all('img')\n",
        "\n",
        "# finds and prints alternative text for images at above url\n",
        "for x in specificData:\n",
        "  print(x['alt'])\n",
        "\n",
        "# source 2\n",
        "\n",
        "# requests data from url below\n",
        "request = requests.get('https://archive.attn.com/stories/7307/common-expressions-words-that-are-sexist')\n",
        "content = request.content\n",
        "\n",
        "# imports library that allows for us to pick what parts of the content to pull\n",
        "from bs4 import BeautifulSoup\n",
        "\n",
        "# stores all of the site's content\n",
        "soup = BeautifulSoup(content)\n",
        "\n",
        "# filters soup to only display what is specified\n",
        "specificData = soup.find_all('h2')\n",
        "\n",
        "# finds and prints text from chart at above url\n",
        "for z in specificData:\n",
        "  print(z.find(text=True)[3:])\n"
      ],
      "execution_count": 33,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[<img alt=\"1-11\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/111-numeric-1-1.jpg?itok=useoCZgu\" typeof=\"foaf:Image\"/>, <img alt=\"1-11\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/111-numeric-1-1.jpg?itok=useoCZgu\"/>, <img alt=\"100%\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/100-percent-1.jpg?itok=wdS-IR5_\" typeof=\"foaf:Image\"/>, <img alt=\"100%\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/100-percent-1.jpg?itok=wdS-IR5_\"/>, <img alt=\"109/110\" src=\"/sites/default/files/styles/max_650x650/public/2019-08/109110-1.jpg?itok=0CTiDCTp\" typeof=\"foaf:Image\"/>, <img alt=\"109/110\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/2019-08/109110-1.jpg?itok=0CTiDCTp\"/>, <img alt=\"12\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/12-numeric-1.jpg?itok=5Tj7reVd\" typeof=\"foaf:Image\"/>, <img alt=\"12\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/12-numeric-1.jpg?itok=5Tj7reVd\"/>, <img alt=\"13\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/13-numeric-1.jpg?itok=DldiymdE\" typeof=\"foaf:Image\"/>, <img alt=\"13\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/13-numeric-1.jpg?itok=DldiymdE\"/>, <img alt=\"13/52 and 13/90\" src=\"/sites/default/files/styles/max_650x650/public/2019-08/13521390-1.jpg?itok=D4QaZKug\" typeof=\"foaf:Image\"/>, <img alt=\"13/52 and 13/90\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/2019-08/13521390-1.jpg?itok=D4QaZKug\"/>, <img alt=\"14\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/14-numeric-1.jpg?itok=2jhfNKJp\" typeof=\"foaf:Image\"/>, <img alt=\"14\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/14-numeric-1.jpg?itok=2jhfNKJp\"/>, <img alt=\"14 Words\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/14-words-1.jpg?itok=uPtgEqvm\" typeof=\"foaf:Image\"/>, <img alt=\"14 Words\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/14-words-1.jpg?itok=uPtgEqvm\"/>, <img alt=\"1423\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/1423-numeric-1.jpg?itok=JnYph5ed\" typeof=\"foaf:Image\"/>, <img alt=\"1423\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/1423-numeric-1.jpg?itok=JnYph5ed\"/>, <img alt=\"1488\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/1488-numeric-1.jpg?itok=dzXiB8eB\" typeof=\"foaf:Image\"/>, <img alt=\"1488\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/1488-numeric-1.jpg?itok=dzXiB8eB\"/>, <img alt=\"18\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/18-numeric-1.jpg?itok=B_zI7wOn\" typeof=\"foaf:Image\"/>, <img alt=\"18\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/18-numeric-1.jpg?itok=B_zI7wOn\"/>, <img alt=\"21-2-12.\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/21-2-12-numeric-1.jpg?itok=8yjEAbYM\" typeof=\"foaf:Image\"/>, <img alt=\"21-2-12.\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/21-2-12-numeric-1.jpg?itok=8yjEAbYM\"/>, <img alt=\"211 Crew\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/211-crew-1.jpg?itok=tVjKdIFJ\" typeof=\"foaf:Image\"/>, <img alt=\"211 Crew\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/211-crew-1.jpg?itok=tVjKdIFJ\"/>, <img alt=\"23 (hand sign)\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/23-hand-sign-1.jpg?itok=PXo8YwAA\" typeof=\"foaf:Image\"/>, <img alt=\"23 (hand sign)\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/23-hand-sign-1.jpg?itok=PXo8YwAA\"/>, <img alt=\"2316\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/2316-numeric-1.jpg?itok=MUyPHVUK\" typeof=\"foaf:Image\"/>, <img alt=\"2316\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/2316-numeric-1.jpg?itok=MUyPHVUK\"/>, <img alt=\"28\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/28-numeric-1.jpg?itok=vVbMheEm\" typeof=\"foaf:Image\"/>, <img alt=\"28\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/28-numeric-1.jpg?itok=vVbMheEm\"/>, <img alt=\"311\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/311-numeric-1.jpg?itok=EH1eWBW8\" typeof=\"foaf:Image\"/>, <img alt=\"311\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/311-numeric-1.jpg?itok=EH1eWBW8\"/>, <img alt=\"318\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/318-numeric-1.jpg?itok=diXwOO6-\" typeof=\"foaf:Image\"/>, <img alt=\"318\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/318-numeric-1.jpg?itok=diXwOO6-\"/>, <img alt=\"33/6\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/33-6-numeric-1.jpg?itok=QScj6N9S\" typeof=\"foaf:Image\"/>, <img alt=\"33/6\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/33-6-numeric-1.jpg?itok=QScj6N9S\"/>, <img alt=\"38\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/38-numeric-1.jpg?itok=ruK8q8fn\" typeof=\"foaf:Image\"/>, <img alt=\"38\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/38-numeric-1.jpg?itok=ruK8q8fn\"/>, <img alt=\"43\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/43-numeric-1.jpg?itok=81QveLMw\" typeof=\"foaf:Image\"/>, <img alt=\"43\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/43-numeric-1.jpg?itok=81QveLMw\"/>, <img alt=\"5 Words\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/5-words-1.jpg?itok=4reKFUhL\" typeof=\"foaf:Image\"/>, <img alt=\"5 Words\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/5-words-1.jpg?itok=4reKFUhL\"/>, <img alt=\"511\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/511-numeric-1.jpg?itok=if9Ln9qQ\" typeof=\"foaf:Image\"/>, <img alt=\"511\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/511-numeric-1.jpg?itok=if9Ln9qQ\"/>, <img alt=\"737\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/737-numeric-1.jpg?itok=6ChgcYt5\" typeof=\"foaf:Image\"/>, <img alt=\"737\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/737-numeric-1.jpg?itok=6ChgcYt5\"/>, <img alt=\"83\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/83-numeric-1.jpg?itok=KRPr-5tn\" typeof=\"foaf:Image\"/>, <img alt=\"83\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/83-numeric-1.jpg?itok=KRPr-5tn\"/>, <img alt=\"88\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/88-numeric-1.jpg?itok=c-oXKWyB\" typeof=\"foaf:Image\"/>, <img alt=\"88\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/88-numeric-1.jpg?itok=c-oXKWyB\"/>, <img alt=\"88 (hand sign)\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/88-hand-sign-1.jpg?itok=A8zae08s\" typeof=\"foaf:Image\"/>, <img alt=\"88 (hand sign)\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/88-hand-sign-1.jpg?itok=A8zae08s\"/>, <img alt=\"9%\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/9-percent-1.jpg?itok=6uxGtuSt\" typeof=\"foaf:Image\"/>, <img alt=\"9%\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/9-percent-1.jpg?itok=6uxGtuSt\"/>, <img alt=\"ACAB\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/acab-1.jpg?itok=-Xs7Vv_5\" typeof=\"foaf:Image\"/>, <img alt=\"ACAB\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/acab-1.jpg?itok=-Xs7Vv_5\"/>, <img alt=\"Advanced White Society\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/advanced-white-society-1.jpg?itok=k-EcKK4M\" typeof=\"foaf:Image\"/>, <img alt=\"Advanced White Society\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/advanced-white-society-1.jpg?itok=k-EcKK4M\"/>, <img alt=\"AKIA\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/akia-1.jpg?itok=MCaIvLBf\" typeof=\"foaf:Image\"/>, <img alt=\"AKIA\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/akia-1.jpg?itok=MCaIvLBf\"/>, <img alt=\"Alabama Aryan Brotherhood\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/alabama-aryan-brotherhood-1.jpg?itok=4ApVntHg\" typeof=\"foaf:Image\"/>, <img alt=\"Alabama Aryan Brotherhood\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/alabama-aryan-brotherhood-1.jpg?itok=4ApVntHg\"/>, <img alt=\"American Front\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/american-front-1.jpg?itok=CayWPNF3\" typeof=\"foaf:Image\"/>, <img alt=\"American Front\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/american-front-1.jpg?itok=CayWPNF3\"/>, <img alt=\"American Identity Movement\" src=\"/sites/default/files/styles/max_650x650/public/2019-08/aim-1.jpg?itok=BKN6oeav\" typeof=\"foaf:Image\"/>, <img alt=\"American Identity Movement\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/2019-08/aim-1.jpg?itok=BKN6oeav\"/>, <img alt=\"Anti-Antifa\" src=\"/sites/default/files/styles/max_650x650/public/2019-08/antiantifa-1.jpg?itok=Nf0Fnjfg\" typeof=\"foaf:Image\"/>, <img alt=\"Anti-Antifa\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/2019-08/antiantifa-1.jpg?itok=Nf0Fnjfg\"/>, <img alt=\"Anti-Racist is a Code Word for Anti-White\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/anti-racist-1.jpg?itok=wScU2--L\" typeof=\"foaf:Image\"/>, <img alt=\"Anti-Racist is a Code Word for Anti-White\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/anti-racist-1.jpg?itok=wScU2--L\"/>, <img alt=\"Anti-SHARP\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/anti-sharp-1.jpg?itok=_kf1BPqM\" typeof=\"foaf:Image\"/>, <img alt=\"Anti-SHARP\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/anti-sharp-1.jpg?itok=_kf1BPqM\"/>, <img alt=\"Anudda Shoah\" src=\"/sites/default/files/styles/max_650x650/public/2019-08/anuddashoah-1.jpg?itok=hVhIFdp-\" typeof=\"foaf:Image\"/>, <img alt=\"Anudda Shoah\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/2019-08/anuddashoah-1.jpg?itok=hVhIFdp-\"/>, <img alt=\"Arrow Cross\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/arrow-cross-1.jpg?itok=j3g4utEW\" typeof=\"foaf:Image\"/>, <img alt=\"Arrow Cross\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/arrow-cross-1.jpg?itok=j3g4utEW\"/>, <img alt=\"Aryan Brotherhood\" src=\"/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/aryan-brotherhood-1.jpg?itok=7Vg3HT0F\" typeof=\"foaf:Image\"/>, <img alt=\"Aryan Brotherhood\" src=\"https://www.adl.org/sites/default/files/styles/max_650x650/public/images/combating-hate/hate-on-display/c/aryan-brotherhood-1.jpg?itok=7Vg3HT0F\"/>]\n",
            "1-11\n",
            "1-11\n",
            "100%\n",
            "100%\n",
            "109/110\n",
            "109/110\n",
            "12\n",
            "12\n",
            "13\n",
            "13\n",
            "13/52 and 13/90\n",
            "13/52 and 13/90\n",
            "14\n",
            "14\n",
            "14 Words\n",
            "14 Words\n",
            "1423\n",
            "1423\n",
            "1488\n",
            "1488\n",
            "18\n",
            "18\n",
            "21-2-12.\n",
            "21-2-12.\n",
            "211 Crew\n",
            "211 Crew\n",
            "23 (hand sign)\n",
            "23 (hand sign)\n",
            "2316\n",
            "2316\n",
            "28\n",
            "28\n",
            "311\n",
            "311\n",
            "318\n",
            "318\n",
            "33/6\n",
            "33/6\n",
            "38\n",
            "38\n",
            "43\n",
            "43\n",
            "5 Words\n",
            "5 Words\n",
            "511\n",
            "511\n",
            "737\n",
            "737\n",
            "83\n",
            "83\n",
            "88\n",
            "88\n",
            "88 (hand sign)\n",
            "88 (hand sign)\n",
            "9%\n",
            "9%\n",
            "ACAB\n",
            "ACAB\n",
            "Advanced White Society\n",
            "Advanced White Society\n",
            "AKIA\n",
            "AKIA\n",
            "Alabama Aryan Brotherhood\n",
            "Alabama Aryan Brotherhood\n",
            "American Front\n",
            "American Front\n",
            "American Identity Movement\n",
            "American Identity Movement\n",
            "Anti-Antifa\n",
            "Anti-Antifa\n",
            "Anti-Racist is a Code Word for Anti-White\n",
            "Anti-Racist is a Code Word for Anti-White\n",
            "Anti-SHARP\n",
            "Anti-SHARP\n",
            "Anudda Shoah\n",
            "Anudda Shoah\n",
            "Arrow Cross\n",
            "Arrow Cross\n",
            "Aryan Brotherhood\n",
            "Aryan Brotherhood\n",
            "\n",
            "                      \n",
            "Bitch\n",
            "Take it like a man/Man up\n",
            "Like a girl\n",
            "Grow a pair/you don't have the balls\n",
            "Pussy\n",
            "Office mom\n",
            "you regularly use the word \"bitch\"?\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}